### PR TITLE
Fix #9 error with unicode in Location street address 

### LINKED ISSUE #9: Error when creating a location with an accented letter in street address
```
File "/srv/nols_cms_home/venvs/current/local/lib/python2.7/site-packages/djangocms_gmaps/models.py", line 182, in get_direction_url
'address': quote_plus(self.address)
File "/usr/lib/python2.7/urllib.py", line 1304, in quote_plus
s = quote(s, safe + ' ')
File "/usr/lib/python2.7/urllib.py", line 1299, in quote
return ''.join(map(quoter, s))
KeyError: u'\xe9'
```

### PR DESCRIPTION
**Pull request by eechien**

### CODE REVIEW

**Comment by mishbahr** [comment]
Does it make sense to use Django DEFAULT_CHARSET setting?

**Comment by eechien** [comment]
Since the default for that setting is already 'utf-8', it does not makes sense to set that.

**Comment by mishbahr** [comment]
That's what I meant.. instead of hardcoding "utf-8" ... may be we should use that setting instead.

**Comment by eechien** [comment]
I misunderstood you; I will make that change.

**Pull request merged**
